[language-server]
omnisharp = { command = "/home/danruto/.local/share/nvim/mason/bin/omnisharp", args = [ "--languageserver" ] }
rust-analyzer = { command = "/home/danruto/.local/share/nvim/mason/bin/rust-analyzer" }
gopls = { command = "/home/danruto/.local/share/nvim/mason/bin/gopls" }
typescript-language-server = { command = "/home/danruto/.bun/bin/typescript-language-server", args = ["--stdio"], language-id = "typescript" }
vscode-css-language-server = { command = "/home/danruto/.local/share/nvim/mason/bin/vscode-css-language-server", args = ["--stdio"], config = { "provideFormatter" = true }}
vscode-json-language-server =  { command = "/home/danruto/.local/share/nvim/mason/bin/vscode-json-language-server", args = ["--stdio"], config = { provideFormatter = true } }
vscode-html-language-server = { command = "/home/danruto/.local/share/nvim/mason/bin/vscode-html-language-server", args = ["--stdio"], config = { provideFormatter = true } }
lua-language-server = { command = "/home/danruto/.local/share/nvim/mason/bin/lua-language-server" }
pyright-langserver = { command = "/home/danruto/.local/share/nvim/mason/bin/pyright-langserver" }

[[language]]
name = "javascript"
indent = { tab-width = 4, unit = "    " }
[[language]]
name = "jsx"
indent = { tab-width = 4, unit = "    " }
[[language]]
name = "typescript"
indent = { tab-width = 4, unit = "    " }
[[language]]
name = "tsx"
indent = { tab-width = 4, unit = "    " }
[[language]]
name = "css"
indent = { tab-width = 4, unit = "    " }
[[language]]
name = "scss"
indent = { tab-width = 4, unit = "    " }
[[language]]
name = "json"
indent = { tab-width = 4, unit = "    " }
[[language]]
name = "python"
language-servers = [ "pyright-langserver" ]
[[language]]
name = "graphql"
indent = { tab-width = 4, unit = "    " }
[[language]]
name = "html"
indent = { tab-width = 4, unit = "    " }
